json.extract! subscriber_setting, :id, :prefix, :minimum_digits, :account_id, :use_autogenerated_number_as_ppoe_username, :notify_user_account_created, :send_reminder_sms_expiring_payments, :created_at, :updated_at
json.url subscriber_setting_url(subscriber_setting, format: :json)
