


{{baseUrl}}/ip/firewall/filter/set
{{baseUrl}}/ip/firewall/filter/add


{
  "action": "any",
  "address-list": "any",
  "address-list-timeout": "any",
  "chain": "any",
  "comment": "any",
  "connection-bytes": "any",
  "connection-limit": "any",
  "connection-mark": "any",
  "connection-nat-state": "any",
  "connection-rate": "any",
  "connection-state": "any",
  "connection-type": "any",
  "content": "any",
  "disabled": "any",
  "dscp": "any",
  "dst-address": "any",
  "dst-address-list": "any",
  "dst-address-type": "any",
  "dst-limit": "any",
  "dst-port": "any",
  "fragment": "any",
  "hotspot": "any",
  "hw-offload": "any",
  "icmp-options": "any",
  "in-bridge-port": "any",
  "in-bridge-port-list": "any",
  "in-interface": "any",
  "in-interface-list": "any",
  "ingress-priority": "any",
  "ipsec-policy": "any",
  "ipv4-options": "any",
  "jump-target": "any",
  "layer7-protocol": "any",
  "limit": "any",
  "log": "any",
  "log-prefix": "any",
  "nth": "any",
  "numbers": "any",
  "out-bridge-port": "any",
  "out-bridge-port-list": "any",
  "out-interface": "any",
  "out-interface-list": "any",
  "p2p": "any",
  "packet-mark": "any",
  "packet-size": "any",
  "per-connection-classifier": "any",
  "port": "any",
  "priority": "any",
  "protocol": "any",
  "psd": "any",
  "random": "any",
  "realm": "any",
  "reject-with": "any",
  "routing-mark": "any",
  "src-address": "any",
  "src-address-list": "any",
  "src-address-type": "any",
  "src-mac-address": "any",
  "src-port": "any",
  "tcp-flags": "any",
  "tcp-mss": "any",
  "time": "any",
  "tls-host": "any",
  "ttl": "any",
  ".proplist": "any",
  ".query": "array"
}