class SubscriberSettingSerializer < ActiveModel::Serializer
  attributes :id, :prefix, :minimum_digits, :account_id, :use_autogenerated_number_as_ppoe_username, 
  :notify_user_account_created, :send_reminder_sms_expiring_subscriptions,
  
  :use_autogenerated_number_as_ppoe_password, :enable_customer_portal,
   :notify_user_payment_received, :invoice_created_or_paid,
   :expiration_reminder_minutes, :expiration_reminder_hours,:expiration_reminder_days,
   :expiration_reminder, 

  :installation_fee, :subscriber_welcome_message, :lock_account_to_mac

end







