require "test_helper"

class SubscriberSettingsControllerTest < ActionDispatch::IntegrationTest
  setup do
    @subscriber_setting = subscriber_settings(:one)
  end

  test "should get index" do
    get subscriber_settings_url
    assert_response :success
  end

  test "should get new" do
    get new_subscriber_setting_url
    assert_response :success
  end

  test "should create subscriber_setting" do
    assert_difference("SubscriberSetting.count") do
      post subscriber_settings_url, params: { subscriber_setting: { account_id: @subscriber_setting.account_id, minimum_digits: @subscriber_setting.minimum_digits, notify_user_account_created: @subscriber_setting.notify_user_account_created, prefix: @subscriber_setting.prefix, send_reminder_sms_expiring_payments: @subscriber_setting.send_reminder_sms_expiring_payments, use_autogenerated_number_as_ppoe_username: @subscriber_setting.use_autogenerated_number_as_ppoe_username } }
    end

    assert_redirected_to subscriber_setting_url(SubscriberSetting.last)
  end

  test "should show subscriber_setting" do
    get subscriber_setting_url(@subscriber_setting)
    assert_response :success
  end

  test "should get edit" do
    get edit_subscriber_setting_url(@subscriber_setting)
    assert_response :success
  end

  test "should update subscriber_setting" do
    patch subscriber_setting_url(@subscriber_setting), params: { subscriber_setting: { account_id: @subscriber_setting.account_id, minimum_digits: @subscriber_setting.minimum_digits, notify_user_account_created: @subscriber_setting.notify_user_account_created, prefix: @subscriber_setting.prefix, send_reminder_sms_expiring_payments: @subscriber_setting.send_reminder_sms_expiring_payments, use_autogenerated_number_as_ppoe_username: @subscriber_setting.use_autogenerated_number_as_ppoe_username } }
    assert_redirected_to subscriber_setting_url(@subscriber_setting)
  end

  test "should destroy subscriber_setting" do
    assert_difference("SubscriberSetting.count", -1) do
      delete subscriber_setting_url(@subscriber_setting)
    end

    assert_redirected_to subscriber_settings_url
  end
end
