



# config/sidekiq.yml

# Default settings for all environments





default:
  :concurrency: 15
  :queues:
     - [invoices, 3]
     - [client_conf, 3]
     - [default, 5]
     - [radacct, 2]

# Development-specific settings
development:
  :concurrency: 10
  :queues:
     - [invoices, 3]
     - [client_conf, 3]
      - [default, 5]
      - [radacct, 2]
    




  :scheduler:
  :schedule:
    subscription_expiration:
      cron: '*/5 * * * *'  
      class: SubscriptionExpiration


# Production-specific settings
production:
  :queues:
    - default
    - client_conf
    - radacct
    - invoices



















































