



# config/sidekiq.yml

# Default settings for all environments
default:
  :concurrency: 5
  :queues:
    - default

# Development-specific settings
development:
  :queues:
    - default

# Production-specific settings
production:
  :queues:
    - default



# :schedule:
#   router_ping_job:
#     every: ["4m", first_in: "4m"]  # Wait 4 minutes before first run, then every 4 minutes
#     class: "RouterPingJob"
#     queue: default















































