



# config/sidekiq.yml

# Default settings for all environments


:schedule:
  broadcast_radacct_stats:
    every: ["30s"]
    class: "RadSessionsJob"
    queue: radacct



default:
  :concurrency: 5
  :queues:
    - default
    - radacct

# Development-specific settings
development:
  :queues:
    - default
    - radacct


# Production-specific settings
production:
  :queues:
    - default



















































