



# config/sidekiq.yml

# Default settings for all environments





default:
  :concurrency: 15
  :queues:
    - default
    - radacct
    - invoices

# Development-specific settings
development:
  :concurrency: 10
  :queues:
    - default
    - radacct
    - invoices
    


# Production-specific settings
production:
  :queues:
    - default
    - radacct
    - invoices



















































