



# config/sidekiq.yml

# Default settings for all environments





default:
  :concurrency: 5
  :queues:
    - default
    - radacct

# Development-specific settings
development:
  :concurrency: 5
  :queues:
    - default
    - radacct
    


# Production-specific settings
production:
  :queues:
    - default



















































