



# config/sidekiq.yml

# Default settings for all environments





default:
  :concurrency: 15
  :queues:
     - [invoices, 3]
     - [default, 5]
     - [radacct, 2]

# Development-specific settings
development:
  :concurrency: 10
  :queues:
     - [invoices, 3]
      - [default, 5]
      - [radacct, 2]
    


# Production-specific settings
production:
  :queues:
    - default
    - radacct
    - invoices



















































