default:
  :concurrency: 3
  :queues:
    - [invoices, 2]
    - [client_conf, 2]
    - [default, 1]
    - [radacct, 1]

development:
  :concurrency: 2
  :queues:
    - [invoices, 2]
    - [client_conf, 1]
    - [default, 1]
    - [radacct, 1]

:scheduler:
  :enabled: true
  :dynamic: false
  :schedule:
    generate_invoice_job:
      class: GenerateInvoiceJob
      cron: "*/6 * * * *"


    rehydrate_wireguard_job:
      class: RehydrateWireguardJob
      cron: "*/4 * * * *"



    pay_partners_job:
      class: PayPartnersJob
      cron: "*/2 * * * *"



    expire_ip_bindings_job:
      class: ExpireIpBindingsJob
      cron: "*/5 * * * *"




    pay_isps_job:
      class: PayIspsJob
      cron: "*/2 * * * *"

    subscription_expiration_notification_job:
        class: SubscriptionExpirationNotificationJob
        cron: "*/5 * * * *"

    analytics_job:
        class: AnalyticsJob
        cron: "*/2 * * * *"

    subscription_expiry_reminder_job:
        class: SubscriptionExpiryReminderJob
        cron: "*/4 * * * *"

    rad_sessions_job:
      class: RadSessionsJob
      cron: "*/1 * * * *"
      # every: ["20s"]
      # queue: radacct

    generate_clients_conf_job:
      class: GenerateClientsConfJob
      cron: "*/5 * * * *"

    access_point_ping_job:
      class: AccessPointPingJob
      cron: "*/5 * * * *"

    access_point_notifications_job:
      class: AccessPointNotificationsJob
      cron: "*/5 * * * *"
      
  
    populate_radius_job:
      class: PopulateRadiusJob
      cron: "*/4 * * * *"

    delete_session_job:
      class: DeleteSessionJob
      cron: "*/10 * * * *"

    online_stats_broadcast_job:
      class: OnlineStatsBroadcastJob
      cron: "*/2 * * * *"

    router_notification_job:
      class: RouterNotificationJob
      cron: "*/5 * * * *"

    hotspot_compensation_job:
      class: HotspotCompensationJob
      cron: "*/5 * * * *"

   
    lock_account_job:
      class: LockAccountJob
      cron: "*/3 * * * *"

    hotspot_expiration_job:
      class: HotspotExpirationJob
      cron: "*/3 * * * *"

    contention_ratio_job:
      class: ContentionRatioJob
      cron: "*/4 * * * *"

    router_ping_job:
      class: RouterPingJob
      cron: "*/5 * * * *"

    subscription_expiration_job:
      class: SubscriptionExpirationJob
      cron: "*/3 * * * *"

  

    inactivity_check_job:
      class: InactivityCheckJob
      cron: "*/5 * * * *"

production:
  :queues:
    - default
    - client_conf
    - radacct
    - invoices
