class CreateSubscriberSettings < ActiveRecord::Migration[7.1]
  def change
    create_table :subscriber_settings do |t|
      t.string :prefix
      t.string :minimum_digits
      t.integer :account_id
      t.boolean :use_autogenerated_number_as_ppoe_username, default: false
      t.boolean :notify_user_account_created, default: false
      t.boolean :send_reminder_sms_expiring_subscriptions, default: false
      t.integer :account_number_starting_value, default: 0

      t.timestamps
    end
  end
end
