class AddUseAutoGeneratedNumberAsPpOePasswordToSubscriberSettings < ActiveRecord::Migration[7.1]
  def change
    add_column :subscriber_settings, :use_autogenerated_number_as_ppoe_password, :boolean, default: false
  end
end
