require "application_system_test_case"

class SubscriberSettingsTest < ApplicationSystemTestCase
  setup do
    @subscriber_setting = subscriber_settings(:one)
  end

  test "visiting the index" do
    visit subscriber_settings_url
    assert_selector "h1", text: "Subscriber settings"
  end

  test "should create subscriber setting" do
    visit subscriber_settings_url
    click_on "New subscriber setting"

    fill_in "Account", with: @subscriber_setting.account_id
    fill_in "Minimum digits", with: @subscriber_setting.minimum_digits
    check "Notify user account created" if @subscriber_setting.notify_user_account_created
    fill_in "Prefix", with: @subscriber_setting.prefix
    fill_in "Send reminder sms expiring payments", with: @subscriber_setting.send_reminder_sms_expiring_payments
    check "Use autogenerated number as ppoe username" if @subscriber_setting.use_autogenerated_number_as_ppoe_username
    click_on "Create Subscriber setting"

    assert_text "Subscriber setting was successfully created"
    click_on "Back"
  end

  test "should update Subscriber setting" do
    visit subscriber_setting_url(@subscriber_setting)
    click_on "Edit this subscriber setting", match: :first

    fill_in "Account", with: @subscriber_setting.account_id
    fill_in "Minimum digits", with: @subscriber_setting.minimum_digits
    check "Notify user account created" if @subscriber_setting.notify_user_account_created
    fill_in "Prefix", with: @subscriber_setting.prefix
    fill_in "Send reminder sms expiring payments", with: @subscriber_setting.send_reminder_sms_expiring_payments
    check "Use autogenerated number as ppoe username" if @subscriber_setting.use_autogenerated_number_as_ppoe_username
    click_on "Update Subscriber setting"

    assert_text "Subscriber setting was successfully updated"
    click_on "Back"
  end

  test "should destroy Subscriber setting" do
    visit subscriber_setting_url(@subscriber_setting)
    click_on "Destroy this subscriber setting", match: :first

    assert_text "Subscriber setting was successfully destroyed"
  end
end
